### ISSUE TITLE
Ich würde gerne als Contributor hinzugefügt werden.

### ISSUE THREAD

**Issue by Jesus-Cries** [tillmbecker/verteilte-systeme#12]
Hallo liebes Team des verteilte-systeme Repositories,

Ich bin zu dem Entschluss gekommen, dass meine zahlreichen mündlichen Beiträge und Hilfestellungen einen großen Beitrag zum potentiellen Erfolg dieses Projektes beigetragen haben. Aus diesem Grund fordere ich einen Eintrag in der Liste der Contributors.

Sollten Sie diesem Wunsch nicht nachkommen werde ich **rechtliche Schritte** einleiten.

Liebe Grüße,
Leon Obermann

**Comment by tillmbecker** [comment]
Nein,
MfG Anwalt.

**Comment by Jesus-Cries** [comment]
In diesem Fall werde ich leider eine rechtsverbindliche Löschung des Repositories beantragen müssen.
